//************************************************************************************
//**  
//**  Source name:   E:\Git\Iron 3\secondaryStone.fcfx
//**  Title:         
//**  Description:   
//**  Device:        AVR.ATTINY.ATTINY85
//**  
//**  Generated by:  Flowcode v8.0.0.6
//**  Date:          Monday, October 14, 2019 00:22:56
//**  Users:         1
//**  Registered to: 
//**  License key:  PORTB
//**  
//**  
//**  http://www.matrixtsl.com
//**  
//************************************************************************************


#define MX_AVR

#define MX_CAL_AVR

#define MX_CLK_SPEED 8000000

#define FCP_NULL Unconnected_Port

#define MX_USI

#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <avr\io.h>
#include <avr\interrupt.h>
#include <avr\eeprom.h>
#include <avr\wdt.h>

//Configuration Start
//Configuration End

/*========================================================================*\
   Use :???????? ??????????? ????
\*========================================================================*/
#include "E:\Git\Iron 3\Libs\CAL\internals.c"



MX_UINT8 FCLV_LOOP1;


/*========================================================================*\
   Use :panel
       :?????????? ??????????
       :?????????? ??????? ???????
\*========================================================================*/
#define FCV_FALSE (0)
#define FCV_TRUE (1)
MX_GLOBAL MX_UINT8 FCV_CLK = (0x0);
MX_GLOBAL MX_UINT8 FCV_HEAT_LVL = (0x0);
MX_GLOBAL MX_UINT8 FCV_COMPARATOR;
MX_GLOBAL MX_BOOL FCV_UPDATE = (0);


/*========================================================================*\
   Use :???????? ???? ????????? ??????????
\*========================================================================*/
#include "E:\Git\Iron 3\Libs\CAL\includes.c"


/*========================================================================*\
   Use :panel
       :?????????? ????????
\*========================================================================*/


/*========================================================================*\
   Use :???????
\*========================================================================*/
int main()
{
    MCUSR=0x00;
    wdt_disable();

    
    // ???: Loop, ???: Loop: While 1
    while (1)
    {

        // ???: Input, ???: Input: PORTB -> comparator
        FCV_COMPARATOR = GET_PORT_MASK(B,0x10);

        // ???: Calculation, ???: Calculation:
        // ???: Calculation, ???:  clk = comparator / 36
        FCV_CLK = FCV_COMPARATOR / 36;

        // ???: Decision, ???: Decision: heat_lvl != clk?
        if (FCV_HEAT_LVL != FCV_CLK)
        {

            // ???: Calculation, ???: Calculation:
            // ???: Calculation, ???:  heat_lvl = clk
            FCV_HEAT_LVL = FCV_CLK;

            // ???: Output, ???: Output: 255 -> PORTB
            SET_PORT_MASK(B,0x04,(255));

            // ???: Delay, ???: Delay: 50 ms
            FCI_DELAYBYTE_MS(50);

            // ???: Output, ???: Output: 0 -> PORTB
            SET_PORT_MASK(B,0x04,(0));

            // ???: Delay, ???: Delay: 50 ms
            FCI_DELAYBYTE_MS(50);

            // ???: clk call, ???: Loop: Loop clk ???
            for (FCLV_LOOP1=0; (FCLV_LOOP1)<(FCV_CLK); (FCLV_LOOP1)++)
            {

                // ???: Output, ???: Output: 255 -> PORTB
                SET_PORT_MASK(B,0x08,(255));

                // ???: Delay, ???: Delay: 50 ms
                FCI_DELAYBYTE_MS(50);

                // ???: Output, ???: Output: 0 -> PORTB
                SET_PORT_MASK(B,0x08,(0));

                // ???: Delay, ???: Delay: 50 ms
                FCI_DELAYBYTE_MS(50);


            }

        // } else {

        }

        // ???: Delay, ???: Delay: 1 s
        FCI_DELAYBYTE_S(1);


    }

    mainendloop: goto mainendloop;
}



/*========================================================================*\
   Use :Interrupt
\*========================================================================*/





